In [1]:
s = "Hi there ryuk!"
print(s.split())


['Hi', 'there', 'ryuk!']


In [2]:
s = "hello lawliet!"
print(s.split())

['hello', 'lawliet!']


In [5]:
planet = "World"
diameter = 12742
print("The diameter of {} is {} kilometers.".format(planet, diameter))

The diameter of World is 12742 kilometers.


In [4]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])


hello


In [7]:
import numpy

In [6]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
import numpy as np
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [9]:
import numpy as np
array=np.arange(20,36,2)
print("Array of all the even integers from 30 to 70")
print(array)

Array of all the even integers from 30 to 70
[20 22 24 26 28 30 32 34]


In [10]:
import numpy as np
x =  np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
a = np.array([[1,2,3]])
b = np.array([[4,5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
import pandas as pd

data = [{'a': 1, 'b': 2},
        {'a': 10, 'b': 20},
        {'a' : 100, 'b':200}]
  
df = pd.DataFrame(data)
df

a    b
0    1    2
1   10   20
2  100  200

In [14]:
import datetime
import pandas as pd
 
test_date = datetime.datetime.strptime("01-01-2023", "%d-%m-%Y")

K = 41
 
date_generated = pd.date_range(test_date, periods=K)
print(date_generated.strftime("%d-%m-%Y"))

Index(['01-01-2023', '02-01-2023', '03-01-2023', '04-01-2023', '05-01-2023',
       '06-01-2023', '07-01-2023', '08-01-2023', '09-01-2023', '10-01-2023',
       '11-01-2023', '12-01-2023', '13-01-2023', '14-01-2023', '15-01-2023',
       '16-01-2023', '17-01-2023', '18-01-2023', '19-01-2023', '20-01-2023',
       '21-01-2023', '22-01-2023', '23-01-2023', '24-01-2023', '25-01-2023',
       '26-01-2023', '27-01-2023', '28-01-2023', '29-01-2023', '30-01-2023',
       '31-01-2023', '01-02-2023', '02-02-2023', '03-02-2023', '04-02-2023',
       '05-02-2023', '06-02-2023', '07-02-2023', '08-02-2023', '09-02-2023',
       '10-02-2023'],
      dtype='object')


In [15]:
import pandas as pd  
lst = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]] 
      
df = pd.DataFrame(lst, columns =['num', 'name', 'Age']) 
print(df)

   num name  Age
0    1  aaa   22
1    2  bbb   25
2    3  ccc   24
